-- COPIA Y PEGA ESTO EN EL SQL EDITOR DE SUPABASE

-- 1. Crear la tabla (si no existe)
create table if not exists jobs (
  id bigint generated by default as identity primary key,
  title text,
  company text,
  location text,
  description text,
  url text unique,
  source text,
  posted_date date,
  sector text,
  seniority text,
  skills text[],
  company_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. IMPORTANTE: Desactivar RLS (Row Level Security)
-- Esto es CRÍTICO. Si no ejecutas esto, el scraper NO podrá guardar datos 
-- y el dashboard mostrará siempre "No hay datos".
alter table jobs disable row level security;
