-- COPIA Y PEGA ESTO EN EL SQL EDITOR DE SUPABASE

-- 1. Crear la tabla (si no existe)
create table if not exists jobs (
  id bigint generated by default as identity primary key,
  title text,
  company text,
  location text,
  description text,
  url text unique,  -- URL única para evitar duplicados
  source text,
  posted_date date,
  sector text,
  seniority text,
  skills text[],
  company_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. IMPORTANTE: Desactivar RLS (Row Level Security) para permitir escritura simple
alter table jobs disable row level security;
