create table jobs (
  id bigint generated by default as identity primary key,
  title text,
  company text,
  location text,
  description text,
  url text unique,
  source text,
  posted_date date,
  sector text,
  seniority text,
  skills text[],
  company_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);